name: Run-Tests

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ["5.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Test with the dotnet CLI
        run: cd ./api/Tests.Unit && dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      - name: Upload CodeCov Data
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: ./api/Tests.Unit/TestResults/coverage.info # optional
          flags: unittests # optional
          name: api-unit-tests # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
