name: Run-Tests

on:
  pull_request:
    branches:
      - master

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.2.0"
      - run: dotnet build api
      - run: dotnet test api/Tests.Unit
