name: Build-Deploy

on:
  pull_request:
    branches:
      - master

jobs:
  api-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run API Unit Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: api/Tests.Unit
          report_name: api_unit_tests
          report_title: API Unit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
